### PR TITLE
examples: legacy_apps: Fix add default routines for suspend/resume

### PR DESCRIPTION
**Pull request by arnopo**
Fix following build warning introduced in PR #76:

system/linux/machine/generic/platform_info.c:546:3: warning: implicit declaration of function ‘system_suspend’ [-Wimplicit-function-declaration]
  546 |   system_suspend();
      |   ^~~~~~~~~~~~~~

### CODE REVIEW

**Comment by arnopo** [comment]
@bentheredonethat : could you have a look please

**Review by edmooring — APPROVED** [review]
Looks good to go.
